#!/bin/dash
structure=src/structures/linked_list.c

rflag=
while getopts r c
do
    case $c in
    r) rflag=1;;
    esac
done
if [ ! -z "$rflag" ]
then
clang \
          -fuse-ld=mold \
          -Ofast \
          $structure \
          src/*.c \
          -o \
          target/release/out
else
clang \
          -fuse-ld=mold \
          -Weverything \
          $structure \
          src/*.c \
          -o \
          target/out
fi
